-- ESC Studio / Supabase backend schema
-- Run this in Supabase SQL Editor or apply it as a migration.

create extension if not exists pgcrypto;

create table if not exists public.esc_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  slug text primary key,
  name text not null,
  enabled boolean not null default true,
  public_config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.game_content (
  id bigint generated by default as identity primary key,
  game_slug text not null references public.games(slug) on delete cascade,
  content_key text,
  category text,
  kind text not null default 'prompt',
  payload jsonb not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists game_content_game_slug_idx
  on public.game_content(game_slug, is_active, sort_order);

create table if not exists public.game_settings (
  game_slug text primary key references public.games(slug) on delete cascade,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists games_touch_updated_at on public.games;
create trigger games_touch_updated_at
before update on public.games
for each row execute function public.touch_updated_at();

drop trigger if exists game_content_touch_updated_at on public.game_content;
create trigger game_content_touch_updated_at
before update on public.game_content
for each row execute function public.touch_updated_at();

drop trigger if exists game_settings_touch_updated_at on public.game_settings;
create trigger game_settings_touch_updated_at
before update on public.game_settings
for each row execute function public.touch_updated_at();

create or replace function public.is_esc_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.esc_admins
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_esc_admin() from public;
grant execute on function public.is_esc_admin() to anon, authenticated;

alter table public.esc_admins enable row level security;
alter table public.games enable row level security;
alter table public.game_content enable row level security;
alter table public.game_settings enable row level security;

-- Explicit Data API grants. RLS below remains the row-level authorization boundary.
revoke all on table public.esc_admins from anon, authenticated;
revoke all on table public.games from anon, authenticated;
revoke all on table public.game_content from anon, authenticated;
revoke all on table public.game_settings from anon, authenticated;

grant select on table public.esc_admins to authenticated;
grant select on table public.games to anon, authenticated;
grant select on table public.game_content to anon, authenticated;
grant select on table public.game_settings to anon, authenticated;

grant insert, update, delete on table public.games to authenticated;
grant insert, update, delete on table public.game_content to authenticated;
grant insert, update, delete on table public.game_settings to authenticated;

grant usage, select on sequence public.game_content_id_seq to authenticated;

revoke all on function public.touch_updated_at() from public;

drop policy if exists "admin can read own role" on public.esc_admins;
create policy "admin can read own role"
on public.esc_admins
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "public can read enabled games" on public.games;
create policy "public can read enabled games"
on public.games
for select
to anon, authenticated
using (enabled = true or public.is_esc_admin());

drop policy if exists "admins can manage games" on public.games;
create policy "admins can manage games"
on public.games
for all
to authenticated
using (public.is_esc_admin())
with check (public.is_esc_admin());

drop policy if exists "public can read active game content" on public.game_content;
create policy "public can read active game content"
on public.game_content
for select
to anon, authenticated
using (
  (
    is_active = true
    and exists (
      select 1 from public.games g
      where g.slug = game_content.game_slug
        and g.enabled = true
    )
  )
  or public.is_esc_admin()
);

drop policy if exists "admins can manage game content" on public.game_content;
create policy "admins can manage game content"
on public.game_content
for all
to authenticated
using (public.is_esc_admin())
with check (public.is_esc_admin());

drop policy if exists "public can read game settings" on public.game_settings;
create policy "public can read game settings"
on public.game_settings
for select
to anon, authenticated
using (
  exists (
    select 1 from public.games g
    where g.slug = game_settings.game_slug
      and g.enabled = true
  )
  or public.is_esc_admin()
);

drop policy if exists "admins can manage game settings" on public.game_settings;
create policy "admins can manage game settings"
on public.game_settings
for all
to authenticated
using (public.is_esc_admin())
with check (public.is_esc_admin());

create or replace function public.replace_game_content(
  p_game_slug text,
  p_items jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
begin
  if not public.is_esc_admin() then
    raise exception 'not authorized';
  end if;

  if not exists (select 1 from public.games where slug = p_game_slug) then
    raise exception 'unknown game slug';
  end if;

  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'p_items must be a JSON array';
  end if;

  delete from public.game_content where game_slug = p_game_slug;

  for item in select * from jsonb_array_elements(p_items)
  loop
    insert into public.game_content (
      game_slug,
      content_key,
      category,
      kind,
      payload,
      sort_order,
      is_active
    )
    values (
      p_game_slug,
      nullif(item->>'content_key', ''),
      nullif(item->>'category', ''),
      coalesce(nullif(item->>'kind', ''), 'prompt'),
      coalesce(item->'payload', '{}'::jsonb),
      coalesce((item->>'sort_order')::integer, 0),
      coalesce((item->>'is_active')::boolean, true)
    );
  end loop;
end;
$$;

revoke all on function public.replace_game_content(text, jsonb) from public;
grant execute on function public.replace_game_content(text, jsonb) to authenticated;

insert into public.games (slug, name) values
  ('truth-or-dare', 'Truth or Dare'),
  ('one-for-me-one-for-you', 'One for Me · One for You'),
  ('last-thing-you-did', 'Last Thing You Did'),
  ('what-would-you-do-if', 'What Would You Do If...?'),
  ('would-you-rather', 'Would You Rather?'),
  ('most-likely-to', 'Most Likely To'),
  ('hot-seat', 'Hot Seat'),
  ('five-second-challenge', '5 Second Challenge'),
  ('red-flag-green-flag', 'Red Flag / Green Flag'),
  ('taboo', 'Taboo'),
  ('debate-roulette', 'Debate Roulette'),
  ('never-have-i-ever', 'Never Have I Ever')
on conflict (slug) do update
set name = excluded.name;
